### PR TITLE
Added news scraper script

### PR DESCRIPTION
**Pull request by MayankGeek**
Please review it .

### CODE REVIEW

**Comment by akashksinghal** [comment]
Great Work @MayankGeek 
Please do the following before I accept this PR :
- [ ] Add your name and Project Name in the Project List in**README.md**

**Comment by MayankGeek** [comment]
Ok

**Comment by MayankGeek** [comment]
Done please check it.

**Comment by akashksinghal** [comment]
Thanks for contributing.
Do star the repo if you find information here useful!

**Pull request merged**
